Debugging `if`

diff --git a/.github/workflows/taxonomy-version-check.yaml b/.github/workflows/taxonomy-version-check.yaml
--- a/.github/workflows/taxonomy-version-check.yaml
+++ b/.github/workflows/taxonomy-version-check.yaml
@@ -1,26 +1,11 @@
-name: taxonomy-version-check
-
-on:
-  schedule:
-    - cron: '0 0 * 8-11 1' # Monday in every month from August through November.
-  push:
-    branches: [master]
-  pull_request:
-    branches: [master]
-
-env:
-  ISSUE_TITLE: 'eBird taxonomy has updated'
-  ISSUE_BODY: |
-    This issue has been opened by the GitHub Action workflow `taxonomy-version-check`.
-
-    There is an update to the eBird taxonomy. The `rebird::tax` dataset and documentation needs to be updated.    
-
 jobs:
   taxonomy-version-check-job:
     runs-on: ubuntu-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
       R_KEEP_PKG_SOURCE: yes
+    outputs:
+      check-failed: ${{ steps.check-taxonomy-version.outputs.failed }}
     steps:
       - name: checkout-step
         uses: actions/checkout@v4
@@ -37,13 +22,13 @@ jobs:
           extra-packages: local::.
 
       - name: check-taxonomy-version-step
-        continue-on-error: true
         id: check-taxonomy-version
-        run: Rscript -e "testthat::test_file('tests/testthat/test-data.R', load_package = 'source', stop_on_failure = TRUE)"
+        run: |
+          Rscript -e "testthat::test_file('tests/testthat/test-data.R', load_package = 'source', stop_on_failure = TRUE)" && echo "failed::false" >> "$GITHUB_OUTPUT" || echo "failed::true" >> "$GITHUB_OUTPUT" 
 
   check-and-create-issue-job:
     needs: taxonomy-version-check-job
-    if: always() && needs.taxonomy-version-check-job.result == 'failure'
+    if: needs.taxonomy-version-check-job.outputs.check-failed == 'true'
     runs-on: ubuntu-latest
     steps:
       - name: check-issue-step
